apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: hello-world-template
spec:
  params:
    - name: GIT_REPO
      description: hhhh
    - name: GIT_REVISION
      description: ggddd
    - name: APP_NAME
      description: fregrthr
   resourcetemplates:
     - apiVersion: tekton.dev/v1beta1
       kind: PipelineRun
      metadata:
        generate: hello-world-run-
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          - name: hello-world-build
        params:
          - name: GIT_REPO
            value: $(tt.params.)
          - name: 
