apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: hello-world-push
spec:
  bindings:
    - ref: hello-world-binding
  template:
    ref: hello-world-trigger-template
  interceptors:
    - ref:
        name: github
      params:
        - name: secretRef
          value:
            secretName: github-webhook-secret
            secretKey: secret
        - name: eventTypes
          value: ["push"]
