apiVersion: v1
kind: Task
metadata:
  name: npm
spec:
  params:
    - name:
      value:
    - name:
      value:

  workspaces:
    - shared
  steps:
    image: 
    script: |
      xxxxx
  results:
  volumes: