apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: kaniko-build-push
  annotations:
    tekton.dev/displayName: "kaniko build and push (ClusterTask)"
    description: "Build an image with Kaniko and push to a registry. Expects valid dockerconfig.json mounted into /kaniko/.docker if authentication is required."
spec:
  params:
    - name: IMAGE
      description: The image to build and push (e.g. quay.io/user/repo:tag)
    - name: DOCKERFILE
      description: Path to Dockerfile (relative to workspace)
      default: Dockerfile
    - name: CONTEXT
      description: Build context (relative path)
      default: .
  workspaces:
    - name: source
      description: Source workspace
  steps:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      workingDir: /workspace/source
      script: |
        #!/usr/bin/env sh
        set -e
        echo "Running kaniko build..."
        /kaniko/executor --context=dir://$(workspaces.source.path)/$(params.CONTEXT) \
          --dockerfile=$(workspaces.source.path)/$(params.DOCKERFILE) \
          --destination=$(params.IMAGE) \
          --verbosity=info
