apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: npm-test
  annotations:
    tekton.dev/displayName: "npm test (ClusterTask)"
    description: "Install deps and run tests for a Node.js app"
spec:
  workspaces:
    - name: source
      description: The workspace containing source code
  steps:
    - name: install
      image: node:20
      workingDir: /workspace/source
      script: |
        #!/usr/bin/env bash
        set -euo pipefail
        echo "Installing dependencies (ci)..."
        npm ci
    - name: test
      image: node:20
      workingDir: /workspace/source
      script: |
        #!/usr/bin/env bash
        set -euo pipefail
        echo "Running tests..."
        # use npm test; CI-friendly flags can be passed through package.json
        npm test
