apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: lint-code
spec:
  params:
    - name: DIRECTORY
      type: string
      description: Directory containing the code to lint
      default: "source"
  workspaces:
    - name: source
  steps:
    - name: run-lint
      image: node:20
      script: |
        cd $(workspaces.source.path)/$(params.DIRECTORY)
        npm install
        npm run lint