apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: hello-world-build-and-deploy
spec:
  params:
    - name: GIT_REPO
      type: string
      description: The git repository URL to clone
    - name: GIT_REVISION
      type: string
      description: The git revision (branch, tag, commit) to checkout
      default: "master"
    - name: CONTEXT
      type: string
      description: The subdirectory within the repository containing the application code
      default: "."
    - name: IMAGE
      type: string
      description: The image URL to push the built application to
    - name: IMAGE_TAG
      type: string
      description: The tag to use for the pushed image
      default: "latest" 
  workspaces:
  - name: shared-workspace
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask 
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: $(params.CONTEXT)
        - name: deleteExisting
          value: "true"
        - name: sslVerify
          value: "false"
      workspaces:
        - name: output
          workspace: shared-workspace 
    
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: $(params.CONTEXT)
        - name: deleteExisting
          value: "true"
        - name: sslVerify
          value: "false"
    - name: npm-install
      runAfter:
        - fetch-repository
      taskRef:
        resolver: hub
        params:
          - name: catalog
            value: tekton-catalog-task
          - name: kind
            value: task
          - name: type
            value: artifact
          - name: version 
            value: 0.1.1
          - name: name
            value: npm-install
    - name: npm-run-lint
      runAfter:
        - npm-install
      taskRef:
        resolver: hub
        params:
          - name: catalog 
            value: tekton-catalog-task
          - name: kind
            value: task
          - name: type
            value: artifact
          - name: name
            value: goland-build
          - name: version
            value: 0.1.0

 
