apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding 
metadata:
  name: hello-world-binding
spec:
  params:
    - name: git-url
      value:  $(body.clone_url)
    - name: revision
      value: $(body.commit_head.id)
