apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-push-binding
spec:
  params:
    - name: GIT_REPO
      value: $(body.repository.clone_url)
    - name: GIT_REVISION
      value: $(body.head_commit.id)
    - name: IMAGE_NAME
      value: $(body.repository.name)
    