apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: github-push-trigger
spec:
  bindings:
    - ref: github-push-binding
  template:
    ref: github-push-template
  interceptors:
    - ref:
        name: "github"
      params:
        - name: "eventTypes"
          value:
            - "push"
        - name: "secretRef"
          value:
            secretName: github-webhook-secret
            secretKey: secret
    - ref:
        name: "cel"
      params:
        - name: "filter"
          value: " body.ref == 'refs/heads/master'"